### ISSUE TITLE
说实话，我对oss 的sdk讨厌至极

### ISSUE THREAD

**Issue by farsunset** [aliyun/aliyun-oss-java-sdk#116]
引用一个aliyun-sdk-oss 要给我附带好多个全家桶，为什么非要用httpclient？而不是okhttp，还有其他各种json包 真是够了

**Comment by funset** [comment]
我就加了一句
compile 'com.aliyun.oss:aliyun-sdk-oss:3.0.0'
呵呵 给我引用进来了20个jar包

**Comment by iminto** [comment]
大概是阿里外包的人写的代码吧

**Comment by baiyubin** [comment]
您可以继续使用java sdk 2.8.x，jar没有变化。3.x.x一所以引入其他的jar是因为添加了鉴权的一些功能，方便您使用RAM的相关功能，引入了RAM相关的jar包。

**Comment by funset** [comment]
鉴个权加几十个jar包，呵呵。厉害

**Comment by chenjazz** [comment]
@baiyubin java sdk 2.8.x依赖的jar包也不少，就不能自己开发一些功能吗？

**Comment by windhc** [comment]
做的事sdk，应该保持依赖的精简，很多功能完全可以自己实现一下，或者参考一下第三方库的实现，没必要为了一两个方法，就引入一个第三方库
