### ISSUE TITLE
Using jersey 1.x makes this library incompatible with any other that uses 2.x

### ISSUE THREAD

**Issue by flozano** [aliyun/aliyun-oss-java-sdk#123]
Jersey 1.x is really old, everyone moved to 2.x, but by this library using 1.x, we can't use it together with any other lib that uses 2.x.

**Comment by flozano** [comment]
Actually, I don't see any jersey code in this library, but I see it as a dependency in the pom.xml. 
```shell
flozano:~/Projects/java/aliyun-oss-java-sdk (master)$ ag com.sun
pom.xml
32:            <groupId>com.sun.jersey</groupId>
flozano:~/Projects/java/aliyun-oss-java-sdk (master)$ ag jersey
pom.xml
32:            <groupId>com.sun.jersey</groupId>
33:            <artifactId>jersey-json</artifactId>
```

**Comment by fuyufjh** [comment]
Same issue. The dependency `jersey-core` breaks something inside Spark API.
