### ISSUE TITLE
2.2.1版本OSSObjectOperation中getObject返回未正常关闭套接字导致CLOSE_WAIT

### ISSUE THREAD

**Issue by nbzhaosq** [aliyun/aliyun-oss-java-sdk#13]
oss sdk v2.2.1中
com.aliyun.oss.internal.OSSObjectOperation中
public OSSObject getObject(GetObjectRequest getObjectRequest) 方法内部没有将Stream关闭，
外部调用获取到OSSObject后，若不显式地对object进行getContent再关闭，则会导致套接字保持CLOSE_WAIT状态

使用v2.0.1版本时并无此问题，因为方法内部将response安全关闭

**Comment by xingfeng2510** [comment]
@nbzhaosq response都关闭了调用该方法还用来干什么？看下注释，强调用户主动关闭content
