### ISSUE TITLE
关于文件夹和文件排序

### ISSUE THREAD

**Issue by tianyi19970120** [aliyun/aliyun-oss-java-sdk#130]
# issue
* 在当前版本下，模拟文件夹功能在获取文件夹和文件后，在设定maxkey时，是否能优先返回文件夹。
* 当前返回除了系统默认的根据修改时间排序，是否还有其他用户可选择的排序参数设置
* 是否支持对文件夹的重命名
* 是否支持批量上传

**Comment by huiguangjun** [comment]
1. key 只支持按照字典序排序。
2. oss 只有key 的概念，没有文件夹概念，所以是不支持文件夹重命名的。
3. 不支持批量上传
