### ISSUE TITLE
无效的包引用

### ISSUE THREAD

**Issue by lvdougongjue** [aliyun/aliyun-oss-java-sdk#146]
3.1的版本中pom，引用了如下的包
        <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-json</artifactId>
            <version>1.9</version>
        </dependency>
实际代码中没有使用该包的类，而是使用了该包引用的另外一个json包，如下所示。
   <dependency>
            <groupId>org.codehaus.jettison</groupId>
            <artifactId>jettison</artifactId>
            <version>1.1</version>
        </dependency>

把jersey-json 包去掉，单独引用 jettison包可以正常编译。
jersey-json包的1.9版本有点小问题，jersey-core里有 javax.ws.rs.ext.RuntimeDelegate 这个类，这个类里面定义的实现类是com.sun.ws.rs.ext.RuntimeDelegateImpl,而配套的jersey-client-1.9版本没有这个类，配套使用会报错。
jersey-json  的1.18版本是正常的。
另外：为什么不用fastjson？

**Comment by huiguangjun** [comment]
已经移除
