### ISSUE TITLE
示例中 OSSClientBuilder不存在

### ISSUE THREAD

**Issue by zhangbaoning** [aliyun/aliyun-oss-java-sdk#153]
从readme添加maven依赖后，使用例子实例化OSS，但OSSClientBuilder无法导入
`OSS ossClient = new OSSClientBuilder().build(endpoint, accessKeyId, accessKeySecret);`

**Comment by Searlas96** [comment]
加一

**Comment by lialong** [comment]
![image](https://user-images.githubusercontent.com/20311047/46945680-07475a80-d0a8-11e8-9297-a675466a4b6b.png)

**Comment by kilowu** [comment]
官方文档的上的版本号更新一下吧，太误导人了：

https://help.aliyun.com/document_detail/32009.html

**Comment by KSMASTERS** [comment]
版本号没更新，显然是版本不对，OSSClientBuilder和之前介绍的版本不一致
