### ISSUE TITLE
导入后闪退

### ISSUE THREAD

**Issue by ypp0623** [aliyun/aliyun-oss-java-sdk#167]
implementation 'com.aliyun.dpa:oss-android-sdk:2.9.1'
我用这样的方式导入后闪退了

**Comment by Shallwewu** [comment]
> implementation 'com.aliyun.dpa:oss-android-sdk:2.9.1'
> 我用这样的方式导入后闪退了

请去咨询android sdk：https://github.com/aliyun/aliyun-oss-android-sdk
