### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/codec/binary/Base64;

### ISSUE THREAD

**Issue by yanchunlan** [aliyun/aliyun-oss-java-sdk#172]
1> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/codec/binary/Base64;
at com.alibaba.sdk.android.oss.common.utils.BinaryUtil.toBase64String(BinaryUtil.java:21)
 at com.alibaba.sdk.android.oss.common.auth.HmacSHA1Signature.computeSignature(HmacSHA1Signature.java:50)
at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:459)
####################
2>Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.codec.binary.Base64" on path: DexPathList[[zip file "/data/app/com.xianghe.ivy-4_nvzNjrxfm1H9-ezxcI_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.xianghe.ivy-4_nvzNjrxfm1H9-ezxcI_w==/lib/arm, /data/app/com.xianghe.ivy-4_nvzNjrxfm1H9-ezxcI_w==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
####################
3>com.alibaba.sdk.android.oss.ClientException: [ErrorMessage]: Unexpected exception!Failed resolution of: 
at com.alibaba.sdk.android.oss.internal.OSSAsyncTask.getResult(OSSAsyncTask.java:69)
at com.alibaba.sdk.android.oss.internal.InternalRequestOperation.syncPutObject(InternalRequestOperation.java:193)

**Comment by Shallwewu** [comment]
> 1> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/codec/binary/Base64;
> at com.alibaba.sdk.android.oss.common.utils.BinaryUtil.toBase64String(BinaryUtil.java:21)
> at com.alibaba.sdk.android.oss.common.auth.HmacSHA1Signature.computeSignature(HmacSHA1Signature.java:50)
> at com.alibaba.sdk.android.oss.common.utils.OSSUtils.sign(OSSUtils.java:459)
> ####################
> 2>Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.codec.binary.Base64" on path: DexPathList[[zip file "/data/app/com.xianghe.ivy-4_nvzNjrxfm1H9-ezxcI_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.xianghe.ivy-4_nvzNjrxfm1H9-ezxcI_w==/lib/arm, /data/app/com.xianghe.ivy-4_nvzNjrxfm1H9-ezxcI_w==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]
> at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> ####################
> 3>com.alibaba.sdk.android.oss.ClientException: [ErrorMessage]: Unexpected exception!Failed resolution of:
> at com.alibaba.sdk.android.oss.internal.OSSAsyncTask.getResult(OSSAsyncTask.java:69)
> at com.alibaba.sdk.android.oss.internal.InternalRequestOperation.syncPutObject(InternalRequestOperation.java:193)

你这个应该是andriod的sdk，不是java sdk。
