### ISSUE TITLE
putObject 将输入流关闭？

### ISSUE THREAD

**Issue by sculxp** [aliyun/aliyun-oss-java-sdk#173]
PutObjectRequest(String bucketName, String key, InputStream input) 
搞不懂这个接口为什么把InputStream关闭了？
比如实现边解压zip边上传就太丑了，都得解压到文件系统再弄？

**Comment by Shallwewu** [comment]
putObject是个完整的API，包括发送put http请求及返回结果处理，所以会负责把输入流及时关闭，不然容易造成流的泄露。

**Comment by sculxp** [comment]
好的，我自己写文件再上传吧，这东西不是这么容易改，各种重载接口最后都一样了．
