### ISSUE TITLE
Response body is not valid json format.

### ISSUE THREAD

**Issue by bajins** [aliyun/aliyun-oss-java-sdk#181]
# 使用的最新版本aliyun-sdk-oss-2.8.3.jar
![image](https://user-images.githubusercontent.com/30252550/50068211-bf57c780-01ff-11e9-982e-7868971f9c4f.png)
![image](https://user-images.githubusercontent.com/30252550/50068227-d4345b00-01ff-11e9-9884-b577a310680d.png)

**Comment by FunriLy** [comment]
- aliyun-oss-java-sdk 的最新版本是 3.4.0 版本了。
- 从错误提示可知，回调服务器返回给OSS的消息体非 JSON 格式，可以先抓包确认一下消息体是否为Json格式。

**Comment by woytu** [comment]
我是直接看的阿里云官方文档，直接用的官方demo

**Comment by woytu** [comment]
> * aliyun-oss-java-sdk 的最新版本是 3.4.0 版本了。
> * 从错误提示可知，回调服务器返回给OSS的消息体非 JSON 格式，可以先抓包确认一下消息体是否为Json格式。

我是直接看的阿里云官方文档，直接用的官方demo

**Comment by FunriLy** [comment]
@woytu 你设置了回调服务器，是需要回调服务器能够处理OSS发送的Post回调才行呀
参考一下这个Demo吧，https://help.aliyun.com/document_detail/31927.html?spm=a2c4g.11186623.6.658.6eb14382DL1JAm
