### ISSUE TITLE
setProxy无法使用

### ISSUE THREAD

**Issue by rockuw** [aliyun/aliyun-oss-java-sdk#19]
用户使用proxy时发现会报NullPointer错误，代码中发现`DefaultServiceClient`的成员`this.credentialsProvider`没有初始化。
另外缺少proxy的测试case。

**Comment by baiyubin** [comment]
使用如下的代码测试是OK的。
    public static void main(String[] args) throws Throwable {
        String endpoint = "http://oss-cn-hangzhou.aliyuncs.com";
        String accessKeyId = "accessKeyId";
        String accessKeySecret = "accessKeySecret";
        String content = "Hello OSS.";

        ClientConfiguration conf = new ClientConfiguration();
        conf.setProxyHost("oss-cn-hangzhou.aliyuncs.com");
        conf.setProxyPort(80);
        
        OSSClient ossClient = new OSSClient(endpoint, accessKeyId, accessKeySecret, conf);

        ossClient.putObject("bucket-name", "key", new ByteArrayInputStream(content.getBytes()));
        
        ossClient.shutdown();
        
        System.out.println("completed");
    }
请提供下你的测试代码。谢谢。

**Comment by rockuw** [comment]
```java
    ClientConfiguration conf = new ClientConfiguration();
    conf.setProxyHost("oss-cn-hangzhou.aliyuncs.com");
    conf.setProxyPort(80);
    conf.setUsername('xxx');
    conf.setPassword('yyy');

    OSSClient ossClient = new OSSClient(endpoint, accessKeyId, accessKeySecret, conf);

    ossClient.putObject("bucket-name", "key", new ByteArrayInputStream(content.getBytes()));
```

我已经告诉你代码中没有初始化的问题了，看一下代码就这么难吗？

**Comment by baiyubin** [comment]
问题已知。如下代码：
public static void main(String[] args) throws Throwable {
        String endpoint = "http://oss-cn-hangzhou.aliyuncs.com";
        String accessKeyId = "accessKeyId";
        String accessKeySecret = "accessKeySecret";
        String content = "Hello OSS.";

        ClientConfiguration conf = new ClientConfiguration();
        conf.setProxyHost("oss-cn-hangzhou.aliyuncs.com");
        conf.setProxyPort(80);
        conf.setProxyUsername("xxx");
        conf.setProxyPassword("yyy");
        
        OSSClient ossClient = new OSSClient(endpoint, accessKeyId, accessKeySecret, conf);

        ossClient.putObject("bucket-name", "key", new ByteArrayInputStream(content.getBytes()));
        
        ossClient.shutdown();
        
        System.out.println("completed");
    }
抛如下异常：
Exception in thread "main" java.lang.NullPointerException
	at com.aliyun.oss.common.comm.DefaultServiceClient.<init>(DefaultServiceClient.java:96)
	at com.aliyun.oss.OSSClient.<init>(OSSClient.java:273)
	at com.aliyun.oss.OSSClient.<init>(OSSClient.java:229)
	at samples.HelloOSS.main(HelloOSS.java:25)
原因是：DefaultServiceClient.credentialsProvider没有初始化。

**Comment by baiyubin** [comment]
2.3.0已修复
