### ISSUE TITLE
com.aliyun.oss.model.ObjectMetadata#getExpirationTime 空指针异常

### ISSUE THREAD

**Issue by promise2mm** [aliyun/aliyun-oss-java-sdk#191]
/**
     * Gets the {@link Date} value of the "Expires" header in Rfc822 format. If
     * expiration is not set, then the value is null.
     * 
     * @return Expires header's value in Rfc822.
     * @throws ParseException
     *             The value is not in the Rfc822 format.
     */
    public Date getExpirationTime() throws ParseException {
        _**// 如果从metadata里面get出来的超时时间是null，那么DateFormat.parse的时候会拋一个空指针
       // 场景：将当前OssObject 转json的时候， 调用了getExpirationTime方法**_
        return DateUtil.parseRfc822Date((String) metadata.get(OSSHeaders.EXPIRES));
    }

**Comment by Shallwewu** [comment]
fixed in 3.4.1
