### ISSUE TITLE
JDK 11 compatibility

### ISSUE THREAD

**Issue by liaohuqiu** [aliyun/aliyun-oss-java-sdk#210]
This project cannot be compiled in JDK 11.` java.xml.bind (JAXB)` has been removed in JDK 11. 

Classes:

* OSSErrorResult
* JAXBResponseParser

are using this package.

Could be hacked by https://stackoverflow.com/questions/36557308/caused-by-java-lang-classnotfoundexception-com-sun-xml-bind-v2-model-annotatio

**Comment by liaohuqiu** [comment]
For those who suffered `NoClassDefFoundError`

```groovy
dependencies {
    compile 'com.aliyun.oss:aliyun-sdk-oss:3.4.2'
    compile 'com.sun.xml.bind:jaxb-core:2.3.0'
    compile 'com.sun.xml.bind:jaxb-impl:2.3.0'
    compile 'javax.xml.bind:jaxb-api:2.3.0'
    compile 'com.sun.activation:javax.activation:1.2.0'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

**Comment by SakuOtonashi** [comment]
```gradle
android {
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }
}
```
添加依赖参考 [Replacements for deprecated JPMS modules with Java EE APIs](https://stackoverflow.com/a/48204154/11545667)
