### ISSUE TITLE
doesObjectExist

### ISSUE THREAD

**Issue by middleware-tech** [aliyun/aliyun-oss-java-sdk#217]
**问题描述**
调用ossClient.doesObjectExist()超时/无返回

**疑问**
com.aliyun.oss.internal.OSSObjectOperation.getSimplifiedObjectMeta()
方法内额外增加了http请求参数
`params.put("objectMeta", (Object)null);`
实验了几个OSS文件的访问，加了这个参数就出问题。
我想应该是这个参数导致的OSS服务端逻辑的不同。

**Comment by liudanking** [comment]
怎么解决的呢？
