### ISSUE TITLE
User metadata key issue when call API  public PutObjectResult putObject(String bucketName, String key, InputStream input, ObjectMetadata metadata)

### ISSUE THREAD

**Issue by lxdv163** [aliyun/aliyun-oss-java-sdk#225]
User metadata key string has limitation when uploading:
1. "_" is not supported, or else throw SignatureDoesNotMatch exception
2. Upper case letter will be auto transferred to lower case letter after successful saving.

latest version 3.4.2 still has this issue.

**Comment by lxdv163** [comment]
there is no any response to this issue?

**Comment by FunriLy** [comment]
1、"_" is not supported in user metadata key.
2、According to RFC2616, the HTTP Method is case-sensitive, and the Header is indistinguishable. So, the user metadata will be auto transferred to lower case letter.

**Comment by huiguangjun** [comment]
[for issue 2] fixed in (https://github.com/aliyun/aliyun-oss-java-sdk/commit/ecb2e74beced3ef2fd4e7e23186a5e3a7ebafb8b)
