### ISSUE TITLE
How to get the version info of the object

### ISSUE THREAD

**Issue by lightning-pro** [aliyun/aliyun-oss-java-sdk#228]
Hi,
https://help.aliyun.com/document_detail/119331.html?spm=5176.11065259.1996646101.searchclickresult.11e2531dBrkJRk
here we can find the version info the Object in bucket, but how to get it in the java sdk?
in aws s3, there is ListVersionsRequest class and listVersions method in the client. Can anyone tell how to do it in this java sdk?

**Comment by huiguangjun** [comment]
https://www.alibabacloud.com/help/en/object-storage-service/latest/list-objects-3
