### ISSUE TITLE
parent在哪里

### ISSUE THREAD

**Issue by MarsYoung** [aliyun/aliyun-oss-java-sdk#24]
<parent>
        <groupId>com.aliyun</groupId>
        <artifactId>parent-pom</artifactId>
        <version>1.0.2</version>
    </parent>
如题。。

**Comment by baiyubin** [comment]
pom.xml中com.aliyun是阿里云所有mvn项目的父节点。如果您独立编译该项目，可以去除<parent>节点。

**Comment by MarsYoung** [comment]
嗯，3ks，你这个代码的samples可以升级下，感觉被误导了，我把sample的代码拷来用，结果全是原始请求。。

**Comment by baiyubin** [comment]
好的。谢谢您的反馈。
