### ISSUE TITLE
OSSClient.downloadFile method fails if BLOB key contains "+" symbol

### ISSUE THREAD

**Issue by nikita-golovin** [aliyun/aliyun-oss-java-sdk#241]
OSSClient.downloadFile method fails if BLOB key contains "+" symbol - leads to incorrect signature creation.

Tested on com.aliyun.oss:aliyun-sdk-oss versions 3.4.2 and 3.5.0

**Comment by huiguangjun** [comment]
This problem is caused by httpClient 4.5.9 （url normalized change).

And compatible with the httpClient 4.5.9  from com.aliyun.oss:aliyun-sdk-oss versions 3.7.0
