### ISSUE TITLE
使用feign重定向下载文件报错

### ISSUE THREAD

**Issue by zhushuangfei0** [aliyun/aliyun-oss-java-sdk#242]
我使用feign调用我的文件服务下载文件，文件服务使用重定向，重定向文件的签名url以实现下载文件的目的。但是，feign调用在请求我的文件服务时，会自动重定向到签名url，但是feign自动进行的重定向会在请求头设置  "Content-type", "unknown/unknown"   ，这样这次请求会返回403

**Comment by huiguangjun** [comment]
在默认情况下，签名url 不会把Content-type 加入到签名串里。发送请求时，如果你的 请求头带上 Content-type", "unknown/unknown，会导致服务端签名不匹配，所以会返回 403. 

解决方法：不要设置这个请求头。  或者 签名时，加上 content-type 内容。
