### ISSUE TITLE
SimpleGetObjectSample例子里获取异常信息写错了

### ISSUE THREAD

**Issue by LeePui** [aliyun/aliyun-oss-java-sdk#248]
System.out.println("Error Message: " + oe.getErrorCode());
应该是
System.out.println("Error Message: " + oe.getErrorMessage());
不知道理解的对不对。

**Comment by hycao** [comment]
确实写错了。我发了一个合并请求，现在还没有处理。
绝对是自动补全的锅（

**Comment by huiguangjun** [comment]
已经merge
