### ISSUE TITLE
com.aliyun.oss.internal.OSSUtils 使用了一个非JDK方法

### ISSUE THREAD

**Issue by zhuyeqing5828** [aliyun/aliyun-oss-java-sdk#25]
在行457 populateRequestCallback(Map<String, String> headers, Callback callback) 方法中使用了sun.misc.BASE64Encoder 类，该类不是jdk的api，在jre环境中编译失败。

**Comment by baiyubin** [comment]
你好，在jre环境中编译失败？只能在jdk环境编译。请参考一下。http://blog.csdn.net/jbxiaozi/article/details/7351768
