### ISSUE TITLE
OSS Download File 能否支持文件中一部分的并行下载？

### ISSUE THREAD

**Issue by cheyang** [aliyun/aliyun-oss-java-sdk#252]
问题：利用Alluxio初次下载OSS文件（冷加载），当文件较大（比如120MB）时，下载时间较长。比如并发下载可以达到450ms, 而串行下载需要3s。调用oss的代码是

https://github.com/Alluxio/alluxio/blob/master/underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java#L102

需求：目前DownloadFIleRequest支持并发下载，但是仅支持完整文件。如果能够支持startPos，endPos应该就能满足需求。谢谢。

```
req.setRange(startPos, endPos);
```

**Comment by huiguangjun** [comment]
已经支持。
