### ISSUE TITLE
istio 弹性环境篡改http header的key为小写问题

### ISSUE THREAD

**Issue by about-cloud** [aliyun/aliyun-oss-java-sdk#266]
istio 弹性环境会篡改http header的key为小写，所以在http header中 ETag 将变成 etag，任何获取 ETag 的地方都会返回 null 值，所以进一步操作回报空指针异常，如下：

```xml
<dependency>
    <groupId>com.aliyun.oss</groupId>
    <artifactId>aliyun-sdk-oss</artifactId>
    <version>3.7.0</version>
</dependency>
```

> java.lang.NullPointerException: null
> 	at com.aliyun.oss.common.parser.RequestMarshallers$CompleteMultipartUploadRequestMarshaller.marshall(RequestMarshallers.java:491)
> 	at com.aliyun.oss.internal.OSSMultipartOperation.completeMultipartUpload(OSSMultipartOperation.java:169)
> 	at com.aliyun.oss.OSSClient.completeMultipartUpload(OSSClient.java:802)

**Comment by huiguangjun** [comment]
谢谢反馈，内部正在评估修改方案

**Comment by huiguangjun** [comment]
兼容小写的 http header 的修改已经合入，你可以基于这个测试版本 做验证。 
   <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
            <version>3.7.1-a</version>
        </dependency>

**Comment by huiguangjun** [comment]
fix in 3.8.0
