### ISSUE TITLE
oss java-sdk上传文件，返回PutObjectResult的response为null

### ISSUE THREAD

**Issue by Costriod** [aliyun/aliyun-oss-java-sdk#286]
```java
PutObjectResult result = oss.putObject(new PutObjectRequest(bucket, key, bis));
```
上传文件之后，返回一个PutObjectResult对象，该对象有如下属性：
    private String requestId;
    private Long clientCRC;
    private Long serverCRC;
    ResponseMessage response;
    private String eTag;
    private String versionId;
    private InputStream callbackResponseBody;
上传成功之后返回的对象里面response属性为null，我没法确认文件上传请求成功还是失败，我不确定这是否是一个bug

**Comment by Costriod** [comment]
oss版本号
```xml
        <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
            <version>3.8.0</version>
        </dependency>
```

**Comment by zhengbinger** [comment]
同样的问题，是没有返回值还是怎样？ 还是必须要用回调还行？

**Comment by liuweiGL** [comment]
+1，官方的案例太简陋了，一个完整的流程都没跑完。

**Comment by dyb23** [comment]
putObjectRequest.setProcess(""); 这样就可以取到

**Comment by huiguangjun** [comment]
调用 sdk api时，如果有错误，都会抛异常，没有异常抛出来，则说明这次请求是成功的。

**Comment by CNSukidayo** [comment]
哈哈哈,这个问题笑死了,putObjectRequest.setProcess("")可以!
