### ISSUE TITLE
关于依赖aliyun-java-sdk-core版本问题

### ISSUE THREAD

**Issue by lan149** [aliyun/aliyun-oss-java-sdk#310]
因为我需要使用多个阿里云产品，涉及到OSS、Push、短信、STS等，但是我发现这个OSS的SDK所依赖的aliyun-java-sdk-core版本非常老，但是别的比如说push用呃sdk版本就很新，请问如果用新版本是否会有兼容的问题呢？如何做到版本统一啊？

**Comment by huiguangjun** [comment]
3.11.1 版本 已经把aliyun-java-sdk-core 版本升级到 4.5.10 版本
