### ISSUE TITLE
doesObjectExist() error IllegalArgumentException if filename prefixes with slash '/'

### ISSUE THREAD

**Issue by yokzy88** [aliyun/aliyun-oss-java-sdk#317]
**Sample code:**
`oss_client.doesObjectExist("MyBucketName","/myfile.txt");`

**Actual Result:**
Throw error IllegalArgumentException 

**Expected Result:**
Not throwing error, but return boolean True or False.

**SDK version:**
3.8.0

**Comment by huiguangjun** [comment]
对象的名字(object name ) 不能以 / 开头.  这个是在参数校验阶段抛的异常
