### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by shenzhenMirren** [aliyun/aliyun-oss-java-sdk#320]
在大于JDK11的环境中使用ossClient.putObject会报错找不到标题中的类,通过maven自己引用这个类后会签名错误

**Comment by upccup** [comment]
doesObjectExist will throw this error too.

**Comment by huiguangjun** [comment]
https://help.aliyun.com/document_detail/32009.html#section-dqn-fpm-1z
