### ISSUE TITLE
项目Spring boot由2.1.7升级到2.1.8后，下载中文文件名出现乱码

### ISSUE THREAD

**Issue by Orca007** [aliyun/aliyun-oss-java-sdk#331]
简化过的最小maven配置如下（不引入其它任何dependency)：

> 
    <groupId>org.example</groupId>
    <artifactId>oss</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>**2.1.8.RELEASE**</version>
        <relativePath/>
    </parent>

    <dependencies>
        <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
            <version>2.7.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.6.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

代码：

> 
    @Test
    public void uploadToOss() throws Throwable {
        OSS ossClient = getOssClient();
        ObjectMetadata objectMetadata = new ObjectMetadata();
        objectMetadata.setHeader(HttpHeaders.CONTENT_DISPOSITION, "吨车拖车委托单.xml");
        PutObjectResult putObjectResult = ossClient.putObject("bucket", "abcd4315.xml", new File("C:\\吨车拖车委托单.xml"), objectMetadata);
    }

再下载获得的文件名：�?�车�??车�?�??�??.xml，除了‘车’字其它字符都变成乱码，问号char是65533，搜索结果是字符非法，UTF-8解码时出错则转为问号

将上面的spring-boot-starter-parent的版本改为2.1.7.RELEASE后问题消失

**与这个问题同时发生的还有：若userMetadata包含中文，上传文件后服务器会报错SignatureDoesNotMatch**

**Comment by dongja3** [comment]
请问这个问题有啥进展么？
我们也遇到了乱码问题，我们用的boot 版本是：2.3.1.RELEASE

**Comment by huiguangjun** [comment]
这个是httpcore 版本差异引起的。 从 httpcore4.4.12 版本开始，request header 里 非iso-8859-1字符集 的字符都被设置成 '?'.

**Comment by huiguangjun** [comment]
![image](https://user-images.githubusercontent.com/40553369/91711893-4eb23380-ebb9-11ea-91d6-174cb39e2ecb.png)
