### ISSUE TITLE
在模块化项目引入sdk后报错

### ISSUE THREAD

**Issue by piaohailin** [aliyun/aliyun-oss-java-sdk#336]
我的项目是javafx工程，使用了模块化，jdk版本11。
项目中引入oss-sdk后，IDE提示，在module-info.java 中加入 requires aliyun.sdk.oss; ，不然oss无法在类中导入。
在module-info.java 中加入 requires aliyun.sdk.oss后，导致所有独立运行的类（没有默认包）无法启动并且报错：
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules stax.api and java.xml export package javax.xml.stream to module org.apache.logging.log4j.slf4j
项目启动入口类目前也无法启动；

用maven启动工程 有错误提示；
[WARNING] * Required filename-based automodules detected: [aliyun-sdk-oss-3.10.2.jar]. Please don't publish this project to a public artifact repository! *

**Comment by FlameTornado10** [comment]
你解决了嘛

**Comment by Rayccyl** [comment]
遇到同樣的問題 似乎這個sdk是不支持模塊系統的 （我正在尋找jpackage對我的項目進行打包的方法 無果）

**Comment by piaohailin** [comment]
> 你解决了嘛

当时没有，感觉阿里系好多组件一直停留在Java 8

**Comment by woxinfeixiang233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
