### ISSUE TITLE
指定前缀遍历文件 nextmarker不变导致死循环

### ISSUE THREAD

**Issue by samunbest** [aliyun/aliyun-oss-java-sdk#339]
版本 3.10.1

**Comment by huiguangjun** [comment]
麻烦你贴一下 遍历时使用的代码.

**Comment by samunbest** [comment]
> 麻烦你贴一下 遍历时使用的代码.

 OSS ossClient = null;
        try {
//            ossClient = new OSSClient(Env.endpoint, Env.accessId, Env.accessKey);
            ClientBuilderConfiguration configuration = new ClientBuilderConfiguration();
            configuration.setConnectionTimeout(50000);
            ossClient = new OSSClientBuilder().build(Env.endpoint, Env.accessId, Env.accessKey, configuration);

            String marker = null;
            do {
                ListObjectsRequest listObjectsRequest = new ListObjectsRequest();
                listObjectsRequest.setBucketName(bucketName);
                listObjectsRequest.setMarker(marker);
                listObjectsRequest.setEncodingType("url");
                listObjectsRequest.setPrefix(prefix);
                listObjectsRequest.setMaxKeys(500);
                ObjectListing objectListing = ossClient.listObjects(listObjectsRequest);
                List<OSSObjectSummary> objectSummaries = objectListing.getObjectSummaries();
                for (OSSObjectSummary ossObjectSummary : objectSummaries) {
                    long size = ossObjectSummary.getSize();
                    totalSize += size;
                }
                marker = objectListing.getNextMarker();
                System.out.println("nextMarker: " + marker);
            } while (marker != null);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (ossClient != null) {
                ossClient.shutdown();
            }
        }

**Comment by huiguangjun** [comment]
} while (marker != null);   需要修改为   } while (objectListing.isTruncated());

**Comment by samunbest** [comment]
> objectListing.isTruncated()

依然是不行的 去掉 listObjectsRequest.setEncodingType("url");就好了

**Comment by huiguangjun** [comment]
当设置为url时， 你需要做个转换, 具体写法如下:

    // 指定文件名称编码。
    listObjectsRequest.setEncodingType("url");

    ...

    // nextMarker解码。
    if (objectListing.getNextMarker() != null) {
        nextMarker = URLDecoder.decode(objectListing.getNextMarker(), "UTF-8");
    }
