### ISSUE TITLE
3.11.1版本删除aliyun-java-sdk-sts依赖后，基于STS临时授权访问OSS该如何操作呢?

### ISSUE THREAD

**Issue by mostcool** [aliyun/aliyun-oss-java-sdk#340]
3.11.1版本删除aliyun-java-sdk-sts依赖后，基于STS临时授权访问OSS该如何操作呢?

https://help.aliyun.com/document_detail/100624.html?spm=a2c4g.11186623.2.10.767e50fdISOnAR#concept-xzh-nzk-2gb 这个文档里的代码已经不适用了。

**Comment by haiyang1024** [comment]
@mostcool 老哥怎么解决的
