### ISSUE TITLE
deleteVersion方法不存在

### ISSUE THREAD

**Issue by zxiaozhou** [aliyun/aliyun-oss-java-sdk#344]
1. 官网文档有deleteVersion方法，实际引入sdk没有
![image](https://user-images.githubusercontent.com/62740686/97133625-94d4df00-1785-11eb-9940-53d8548bc8b9.png)
2. sdk信息：com.alibaba.cloud:spring-cloud-starter-alicloud-oss:2.2.0.RELEASE
3. 还有请问下spring-cloud-starter-alicloud-oss与aliyun-sdk-oss有啥区别，两个都需要自己创建OSSClient，官方没有文档说明

**Comment by huiguangjun** [comment]
com.alibaba.cloud:spring-cloud-starter-alicloud-oss:2.2.0  包是依赖 aliyun-sdk-oss

deleteVersion 接口是 aliyun-sdk-oss 3.5.0 版本引入的。 

如果不存在，请检查项目的版本依赖。
