### ISSUE TITLE
SSL的TrustManager需要判断空值，否则可能引起空指针错误

### ISSUE THREAD

**Issue by edwinwang888** [aliyun/aliyun-oss-java-sdk#346]
修改DefaultServiceClient，将下面注释掉的代码改为加入空值判断
        public X509Certificate[] getAcceptedIssuers() {
            List<X509Certificate> certificates = new ArrayList<X509Certificate>();
            for (X509TrustManager trustManager : trustManagers) {
                //certificates.addAll(Arrays.asList(trustManager.getAcceptedIssuers()));
            	X509Certificate[] accepts =trustManager.getAcceptedIssuers();
            	if(accepts != null && accepts.length > 0) {
            		certificates.addAll(Arrays.asList(accepts));
            	}
            }
            X509Certificate[] certificatesArray = new X509Certificate[certificates.size()];
            return certificates.toArray(certificatesArray);
        }

**Comment by huiguangjun** [comment]
已经修复， 合入到 开发分支里
