### ISSUE TITLE
通过临时秘钥初始化的ossClient客户端如何能够更新临时秘钥，没有发现对应的API

### ISSUE THREAD

**Issue by bai597030001** [aliyun/aliyun-oss-java-sdk#353]
通过临时秘钥初始化的ossClient客户端如何能够更新临时秘钥，没有发现对应的API

**Comment by huiguangjun** [comment]
可以基于 CredentialsProvider 方式来 动态更新 ak/sk 或 ak/sk/token。

类似写法如下： 
InstanceProfileCredentialsProvider provider = CredentialsProviderFactory.newInstanceProfileCredentialsProvider("ecs-ram-role");
 OSS ossClient = new OSSClientBuilder().build(endpoint, provider, new ClientBuilderConfiguration()

具体的示例可以参考：
https://github.com/aliyun/aliyun-oss-java-sdk/tree/master/src/main/java/com/aliyun/oss/common/auth
