### ISSUE TITLE
mime.types资源文件与其他SDK冲突，导致不能自动识别MimeType

### ISSUE THREAD

**Issue by YuanWenqing** [aliyun/aliyun-oss-java-sdk#357]
OSS sdk中资源文件mime.types与其他sdk的资源文件重名了，比如：

* software.amazon.awssdk:sdk-core
* io.reactivex:rxnetty
* org.springframework:spring-web
* org.springframework:spring-context-support
* ...

这些sdk中mime.types的格式保持一致，即第一列是MimeType，第二列是 extension，即使互相干扰有问题也只是覆盖范围的问题。
但是阿里云OSS sdk中的格式正好与它们相反，在实际使用过程中，由于类加载顺序的问题导致与上面这些sdk的资源文件互相干扰，最终无法有效识别 MimeType。

建议：
* 更改资源文件名称，加上aliyun特有的前缀。 #355 中尝试添加了 oss 前缀
* 或者修改文件格式，与其他sdk保持格式一致

**Comment by huiguangjun** [comment]
3.11.3 版本已修复
