### ISSUE TITLE
分片上传返回的PartETag问题

### ISSUE THREAD

**Issue by archine** [aliyun/aliyun-oss-java-sdk#359]
Java版本，我看了下使用方式，在java端进行文件切割，如果文件过大，岂不是造成jvm的堆栈溢出，除非jvm的堆栈大小设置的大于文件2倍。所以这种还是前端进行切割，然后前端通过多个请求同时调用Java这边的分片上传。但是你只在每次调用返回一个partETage，后面没有通过uploadID查询这个文件的所有partETag，这样，就需要额外的找一个地方存储文件的所有partETag，每次上传成功一个分片就得取出来更新下

**Comment by woxinfeixiang233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
