### ISSUE TITLE
oss下载报错，是否是引用的httpcomponents有问题

### ISSUE THREAD

**Issue by jgswp** [aliyun/aliyun-oss-java-sdk#360]
![图片](https://user-images.githubusercontent.com/35256326/109135411-00f63c80-7792-11eb-91df-7b6d180e2158.png)

**Comment by huiguangjun** [comment]
请参考  https://help.aliyun.com/document_detail/32024.html?spm=a2c4g.11186623.6.993.1d69295f0AZFtZ  中的 “连接关闭”  说明
