### ISSUE TITLE
bug 提交

### ISSUE THREAD

**Issue by zhuyeqing5828** [aliyun/aliyun-oss-java-sdk#37]
在测试使用该SDK 时发现几个bug

当 put 时 Object 的key 为 “” （空字符串）时，会抛出IndexOutOfBoundException 在 OSSUtil 的98行
当 put 时 设置Content-Length 大于inputStream内容的实际长度，会导致IO阻塞，之后抛出session连接超时异常。

**Comment by baiyubin** [comment]
非常感谢您的反馈。我们将规划修复您反馈的问题。

**Comment by baiyubin** [comment]
OSSO您好，V2.5.0中修复了第一个问题。
