### ISSUE TITLE
Unsupported algorithm: HmacSHA1

### ISSUE THREAD

**Issue by chenjinkai** [aliyun/aliyun-oss-java-sdk#38]
试过将jre ext包下面的sunjce_provider.jarcopy到tomcat下，也看到过java.security文件，已经配置上了。

**Comment by baiyubin** [comment]
感谢您的反馈。

**Comment by huangjide** [comment]
我已经把$JRE_HOME/lib/ext 加入到classpath中，但是还是会报上面的错误，请问为什么呢？
