### ISSUE TITLE
DeleteObjectsResult's constructor may throw an NPE

### ISSUE THREAD

**Issue by zbjice** [aliyun/aliyun-oss-java-sdk#390]
now:
public DeleteVersionsResult(List<DeletedVersion> deletedVersions) {
            this.deletedVersions.addAll(deletedVersions);
}

fixed:
public DeleteVersionsResult(List<DeletedVersion> deletedVersions) {
    if (deletedVersions != null && deletedVersions.size() > 0) {
        this.deletedVersions.addAll(deletedVersions);
    }
}

**Comment by huiguangjun** [comment]
fix in c475a33b0d5c2f2b536941504143f46709f68c42
