### ISSUE TITLE
断点下载到NAS时并发写没有4KB对齐，导致写NAS延时上涨

### ISSUE THREAD

**Issue by rockuw** [aliyun/aliyun-oss-java-sdk#397]
目前只按文件大小/线程数划分，没有4KB对齐，当下载到NAS时，会造成写前读，延时增加5倍。

**Comment by huiguangjun** [comment]
https://github.com/aliyun/aliyun-oss-java-sdk/commit/59e85c6d2e3347e0f42b02d437f990bdae66ef21
