### ISSUE TITLE
RSA key is passed as string instead of byte[]

### ISSUE THREAD

**Issue by akwick** [aliyun/aliyun-oss-java-sdk#405]
During an empirical study to understand the nature of cryptographic misuses in enterprise-driven projects on GitHub, we randomly inspected a few of the misuses. One of the misuses for which we could confirm as a true positive of the analysis, [CogniCryptSAST](https://github.com/CROSSINGTUD/CryptoAnalysis), is in this project. 
In the class [SimpleRSAEncryptionMaterials](https://github.com/aliyun/aliyun-oss-java-sdk/blob/a20476417c709f80275fdff55a70eb83685b2577/src/main/java/com/aliyun/oss/crypto/SimpleRSAEncryptionMaterials.java), a key, e.g. [line 196](https://github.com/aliyun/aliyun-oss-java-sdk/blob/a20476417c709f80275fdff55a70eb83685b2577/src/main/java/com/aliyun/oss/crypto/SimpleRSAEncryptionMaterials.java#L196) is passed as a string and that is considered insecure. In Java, strings are immutable and stay in memory until collected by Java's garbage collector. Thus, they are longer visible in memory for attackers than necessary and outside of the direct control of the developer. The suggested data types by the JCA are bytes. [JCA Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/security/crypto/CryptoSpec.html#PBEEx)

Thus, the observed usage is a misuse of the JCA API. 

### Steps to reproduce

1. Apply CogniCryptSAST to the project
2. Inspect the misuses reported

**Comment by woxinfeixiang233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by akwick** [comment]
During a study to label real-world JCA usages, we, @schlichtig and I, observed the use of a string for sensitive information in another case. 

In the method [getPrivateKeyFromPemPKCS8](https://github.com/aliyun/aliyun-oss-java-sdk/blob/3f0a1a8046aa9312fdd2030218367f4c719dcfad/src/main/java/com/aliyun/oss/crypto/SimpleRSAEncryptionMaterials.java#L45) a private key is handled as key.

**Comment by woxinfeixiang233** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
