### ISSUE TITLE
parameter validation error

### ISSUE THREAD

**Issue by luryson** [aliyun/aliyun-oss-java-sdk#408]
https://github.com/aliyun/aliyun-oss-java-sdk/blob/516699cd74e0c115b61be2a2dd81d75a740ca81a/src/main/java/com/aliyun/oss/crypto/KmsEncryptionMaterials.java#L59

**Comment by huiguangjun** [comment]
https://github.com/aliyun/aliyun-oss-java-sdk/commit/ba656f57a98b81b21a5813ed5a9be0db82e2a295
