### ISSUE TITLE
aliyun oss有没有比较详尽的 demo?

### ISSUE THREAD

**Issue by theseusyang** [aliyun/aliyun-oss-java-sdk#47]
Hi All:

aliyun oss有没有调用主要功能的比较详尽的 demo? 用于应用开发参考.

**Comment by baiyubin** [comment]
src/sample目录下的文件为示例文件，https://github.com/aliyun/aliyun-oss-java-sdk/tree/master/src/samples

**Comment by theseusyang** [comment]
恩, 有没有把 sample 中的功能点穿起来的 demo? :)

**Comment by baiyubin** [comment]
非常抱歉，目前还没有。
