### ISSUE TITLE
aliyun oss 有TransferManager这个方法吗？

### ISSUE THREAD

**Issue by theseusyang** [aliyun/aliyun-oss-java-sdk#48]
在 aws 的 s3上有TransferManagerd的方法可以对s3的传输进行管理，aliyun oss 有类似TransferManager的方法吗？

**Comment by baiyubin** [comment]
OSS有类似的功能，叫断点续传，详细请参考 [断点续传上传](https://help.aliyun.com/document_detail/32013.html)，[断点续传下载](https://help.aliyun.com/document_detail/32014.html?spm=5176.doc32013.6.215.NYn1qC)。

**Comment by theseusyang** [comment]
恩，aws 的TransferManager 承担这管理 Client 生命周期的作用, 看来TransferManager的功能已经被打散，分散到 OSS 的 OSSClient, Upload, Download 中.

**Comment by baiyubin** [comment]
是的。
