### ISSUE TITLE
通过OSS-SDK获得的文件流，在没有完全读完的情况下不能关闭。

### ISSUE THREAD

**Issue by lephix** [aliyun/aliyun-oss-java-sdk#57]
当处理大文件的时候，有时只需要读取部分数据，或者根据读取数据内容来判断是否继续往下读取。这时，可能没有读完整个流的情况下就已经完成了业务操作。需要关闭流，这时流不能被关闭，线程会被卡住。
已经在钉钉内和@李文兆 @鸣镝沟通了，建议提供一个类似forceClose()的方法。
下面是卡住线程的堆栈信息：

    Stack trace: 
    java.net.SocketInputStream.socketRead0(Native Method)
    java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    java.net.SocketInputStream.read(SocketInputStream.java:170)
    java.net.SocketInputStream.read(SocketInputStream.java:141)
    org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
    org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:200)
    org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
    org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:200)
    org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:103)
    org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:128)
    org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
    org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
    java.io.FilterInputStream.close(FilterInputStream.java:181)
    com.aliyun.oss.event.ProgressInputStream.close(ProgressInputStream.java:147)
    cn.mucang.oort.transfer.action.api.open.OSSFileAction.get(OSSFileAction.java:137)  
    ...

**Comment by baiyubin** [comment]
您好，V2.5.0中修复了该问题，添加了forcedClose接口。
