### ISSUE TITLE
设计一致性原则【谁分配谁释放】

### ISSUE THREAD

**Issue by goodname008** [aliyun/aliyun-oss-java-sdk#63]
OSSObject里封装了一个InputStream，建议OSSObject实现一下Closeable接口，在close方法的实现里把这个InputStream关一下，以免上层调用者忘记关闭导致资源泄漏。

**Comment by baiyubin** [comment]
非常感谢您的反馈，将在下个版本中修复该问题。

**Comment by baiyubin** [comment]
您好，V2.5.0中修复了该问题。
