### ISSUE TITLE
通过OSSClient.getBucketInfo.getBucket.getIntranetEndpoint获取的值是null

### ISSUE THREAD

**Issue by canghailan** [aliyun/aliyun-oss-java-sdk#64]
com.aliyun.oss.internal.ResponseParsers#parseGetBucketInfo中未解析ExtranetEndpoint、IntranetEndpoint

**Comment by baiyubin** [comment]
非常感谢您的反馈，将在下个版本中修复该问题。

**Comment by baiyubin** [comment]
您好，V2.5.0中修复了该问题。
