### ISSUE TITLE
创建直播对象，检查oss控制台，无直播推流对象文件夹生成

### ISSUE THREAD

**Issue by yigemaser** [aliyun/aliyun-oss-java-sdk#68]
ossClient.putObject(bucketName, "ggggg/", new ByteArrayInputStream(new byte[0]));
	 CreateLiveChannelRequest createLiveChannelRequest = new CreateLiveChannelRequest(
		                    bucketName, “hello”);
		            ossClient.createLiveChannel(createLiveChannelRequest);
第一行能够执行成功，在oss的bucket中生成“ggggg”对象文件夹，这个只是测试用，顺序执行完，不报任何错误，但是oss的buket里面没有“hello”直播推流文件夹生成。
分别用oss 2.4.0和2.4.1版本，都不行

**Comment by yigemaser** [comment]
哎，找到问题了，生成是生成了，在控制台是看不见的，只有推流成功了才能在控制台看见文件夹。

**Comment by baiyubin** [comment]
您好，目前控制台上无法查看livechannel，可以通过listLiveChannels或getLiveChannelInfo查看。
