### ISSUE TITLE
UploadFileRequest不支持UploadProgressListener？

### ISSUE THREAD

**Issue by zhangqianliang** [aliyun/aliyun-oss-java-sdk#71]
UploadFileRequest时添加UploadProgressListener，但是没有看到相关进度的回调。文件是上传成功了。

    UploadFileRequest uploadFileRequest = new UploadFileRequest("nsvod", "data/60_1.mp4");
    uploadFileRequest.setUploadFile("/usr/local/var/www/vod/file/60_1.mp4");
    uploadFileRequest.setTaskNum(1);
    uploadFileRequest.setPartSize(2 * 1024 * 1024);
    uploadFileRequest.setEnableCheckpoint(true);
    uploadFileRequest.setProgressListener(new UploadProgressListener());
    UploadFileResult uploadResult = ossClient.uploadFile(uploadFileRequest);

**Comment by baiyubin** [comment]
您好，断点上传下载尚不支持进度条功能，开发评估开发。
