### ISSUE TITLE
整点上传失败！

### ISSUE THREAD

**Issue by dzxiang** [aliyun/aliyun-oss-java-sdk#73]
通过OSSClient的putObject上传文件，如果上传的时候正好是整点，比如，10:00:00或14:00:00，上传的时候没有出现异常，但实际上文件并没有保存在OSS上，非整点的时候没有出现这个问题。

使用V2.4.0 或 V2.5.0，都有这个问题。

**Comment by baiyubin** [comment]
谢谢您的反馈。您提供的信息比较有限，请您直接旺旺联系`oss_support`，或[提交工单](https://selfservice.console.aliyun.com/ticket/createIndex)解决该问题。
