### ISSUE TITLE
ossclient 分片上传问题

### ISSUE THREAD

**Issue by maregeo** [aliyun/aliyun-oss-java-sdk#74]
分片上传OSSclient 目前好像只支持单例模式，ossClient 不能复用。
1，示例下的MultipartUploadSample这个类中，调用了线程池

 `  private static ExecutorService executorService = Executors.newFixedThreadPool(5);`
声明为全局变量
如果ossclient为单例，那么
```
/*
             * Waiting for all parts finished
             */
            executorService.shutdown();
            while (!executorService.isTerminated()) {
                try {
                    executorService.awaitTermination(5, TimeUnit.SECONDS);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
```
这段代码逻辑就有问题了。并发条件下，线程池的线程非一个用户在使用
eg：
比如A用途提交了10M的文件正好2个分片，B用户提交了10M的文件，正好2个分片。假设A的2个分片先上传好了，B的正在上传。那么这个时候A还在等待线程池的所有线程执行完毕。这个地方觉得不合理了。
如果说把线程池放在方法内，作为方法的局部变量，那么频换的创建和销毁线城市，是否不妥？
以上是个人的理解，还请赐教

**Comment by baiyubin** [comment]
您好，MultipartUploadSample只是一个应用实例。OSSclient可以不是单例的；并发上传下载，请有限使用OSSclient.uploadFile和OSSclient.downloadFile。
