### ISSUE TITLE
阿里云 OSS Java SDK 对 JDOM 1.1 版本的引用会阻止 maven bundle 插件工作

### ISSUE THREAD

**Issue by chzhong** [aliyun/aliyun-oss-java-sdk#75]
阿里云 OSS Java SDK 引用了 JDOM 1.1 版本（2008年9月发布）
这个依赖库由于在默认包（root package）下有类，导致 maven-bundle-plugin 打包 jar 时出错：

> The default package '.' is not permitted by the Import-Package syntax

这会使得引用阿里云 Java SDK 开发者无法正常使用 maven 打包自己的 jar。

JDOM 1.1.2、1.1.3 （分别于2011年11月、2012年12月发布）移除了默认包下的类。
JDOM 最新的版本是 2.0.6，www.jdom.org 上建议更新到最新版本。（Apache Maven 上能找到的最新版本是 2.0.2）
已经确认，在 pom 文件中强制引用 1.1.3 会临时解决此问题。

建议更新 JDOM 的引用版本修正此问题，版本升级攻略 https://github.com/hunterhacker/jdom/wiki/JDOM2-Migration-Issues。

参考：
http://stackoverflow.com/questions/33395100/the-default-package-is-not-permitted-by-the-import-package-syntax 
https://techotom.wordpress.com/2014/10/21/fixing-the-default-package-is-not-permitted-by-the-import-package-syntax-with-maven-bundle-plugin/

**Comment by baiyubin** [comment]
非常感谢您的反馈，我们正在评估JDOM的版本。

**Comment by nickfan** [comment]
@baiyubin 大概还要评估多久？2019年了。。

**Comment by huiguangjun** [comment]
https://github.com/aliyun/aliyun-oss-java-sdk/commit/ed47fe25c9f5529d642ab27b28489c0a3a4ced7a
