### ISSUE TITLE
分片上传回调

### ISSUE THREAD

**Issue by NanYoMy** [aliyun/aliyun-oss-java-sdk#8]
hi， 这里面有没有关于分片上传的回调的demo,在completeMultipartUpload中添加callback，我发现调用completeMultipartUpload后的返回是个CompleteMultipartUploadResult，这里面完全都没有是否调用成功的信息和我web服务器返回的给客户端的参数。

**Comment by baiyubin** [comment]
分片上传的demo请参考https://github.com/aliyun/aliyun-oss-java-sdk/blob/master/src/test/java/com/aliyun/oss/integrationtests/CallbackTest.java。completeMultipartUpload没有抛异常就是调用成功，不成功会抛异常的。
