### ISSUE TITLE
判断bucket是否存在，逻辑上有bug

### ISSUE THREAD

**Issue by demonwy** [aliyun/aliyun-oss-java-sdk#81]
(1)代码位置：
https://github.com/aliyun/aliyun-oss-java-sdk/blob/master/src/main/java/com/aliyun/oss/internal/OSSBucketOperation.java#L390

(2)问题描述
当server返回非NO_SUCH_BUCKET的错误的时候，会返回true.

(3)期望结果
catch中只处理需要的error，否则都向上抛

**Comment by baiyubin** [comment]
您好，该问题已经在 `2.6.0` 中修复。
