### ISSUE TITLE
阿里云的SDK居然不用自家的fastjson作为JSON序列化工具？

### ISSUE THREAD

**Issue by CodePlayer** [aliyun/aliyun-oss-java-sdk#88]
如题。发现OSS的SDK用的还是json-lib，而不是自家的fastjson。

**Comment by chinaluopiao** [comment]
如题。发现OSS的SDK用的还是json-lib，而不是自家的fastjson。

**Comment by takeseem** [comment]
关键是还是性能最差的json-lib.建议使用jackson-json

**Comment by windhc** [comment]
**非常建议使用jackson、gson或者fastjson，谢谢**

**Comment by duhanmin** [comment]
fastjson太烂了

**Comment by huiguangjun** [comment]
oss sdk 不依赖json 库， 已经移除对json 库的直接依赖。
